# Generated by Django 5.1.4 on 2025-01-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.IntegerField(),
        ),
    ]
