# Generated by Django 5.1.4 on 2025-01-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='identity_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
