# Generated by Django 5.1.4 on 2025-01-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_identity_number_booking_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='identity_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone_number',
        ),
    ]
