# Generated by Django 5.1.4 on 2025-01-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_room_quantity_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rooms_booked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
