# Generated by Django 5.1.4 on 2025-01-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_rooms_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
    ]
