# Generated by Django 5.1.4 on 2025-01-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_remove_room_image_alter_room_room_type_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/media/'),
        ),
    ]
